apiVersion: v1
kind: Service
metadata:
  name: fresh-portal
  labels:
    app.kubernetes.io/name: fresh-portal
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: fresh-portal
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
