apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml
  - poddisruptionbudget.yaml

namespace: fresh-production

patches:
  - path: deployment-patch.yaml

images:
  - name: fresh-portal
    newName: harbor.example.com/honglam/fresh-portal
    digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
