apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hl-fresh
  labels:
    app.kubernetes.io/name: hl-fresh
    app.kubernetes.io/component: frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hl-fresh
